"""add_business_info_table

Revision ID: 035570aa5a29
Revises: a3b9030af8fc
Create Date: 2026-07-22 12:31:17.910541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035570aa5a29'
down_revision: Union[str, Sequence[str], None] = 'a3b9030af8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_info',
    sa.Column('company_name', sa.String(length=256), nullable=False),
    sa.Column('ruc', sa.String(length=13), nullable=False),
    sa.Column('legal_representative', sa.String(length=256), nullable=True),
    sa.Column('bank_name', sa.String(length=128), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('account_number', sa.String(length=32), nullable=False),
    sa.Column('support_email', sa.String(length=256), nullable=True),
    sa.Column('support_phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_info')
    # ### end Alembic commands ###
