"""add_email_to_contacts

Revision ID: 0e46a7aff548
Revises: 644fdd6ef5fe
Create Date: 2026-07-12 21:04:53.618977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e46a7aff548'
down_revision: Union[str, Sequence[str], None] = '644fdd6ef5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('email', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'email')
    # ### end Alembic commands ###
