"""add_subscription_plans_user_profiles_onboarding

Revision ID: 228f6423df6c
Revises: 0e46a7aff548
Create Date: 2026-07-18 23:30:16.469249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '228f6423df6c'
down_revision: Union[str, Sequence[str], None] = '0e46a7aff548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('price_monthly_usd', sa.Float(), nullable=False),
    sa.Column('price_annual_usd', sa.Float(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_slug'), 'subscription_plans', ['slug'], unique=True)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('id_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('privacy_policy_accepted', sa.Boolean(), nullable=False),
    sa.Column('privacy_policy_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.add_column('payments', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('payments', sa.Column('payment_method', sa.Enum('credit_card', 'debit_card', 'deposit', 'transfer', 'cash', 'other', name='payment_method'), nullable=False))
    op.alter_column('payments', 'gateway',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    op.add_column('subscriptions', sa.Column('plan_id', sa.UUID(), nullable=False))
    op.add_column('subscriptions', sa.Column('payment_method', sa.Enum('credit_card', 'debit_card', 'deposit', 'transfer', 'cash', 'other', name='payment_method'), nullable=True))
    op.add_column('subscriptions', sa.Column('renewal_type', sa.Enum('monthly', 'annual', name='renewal_type'), nullable=True))
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    op.drop_column('subscriptions', 'plan')
    op.add_column('users', sa.Column('preferred_name', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('onboarding_complete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_complete')
    op.drop_column('users', 'preferred_name')
    op.add_column('subscriptions', sa.Column('plan', postgresql.ENUM('free', 'individual', 'ruc', name='subscription_plan'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'renewal_type')
    op.drop_column('subscriptions', 'payment_method')
    op.drop_column('subscriptions', 'plan_id')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.alter_column('payments', 'gateway',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('payments', 'payment_method')
    op.drop_column('payments', 'user_id')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_subscription_plans_slug'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
