"""add_billing_models_for_quotes

Revision ID: 266d907466a2
Revises: d629ec20422f
Create Date: 2026-07-22 15:32:28.836246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266d907466a2'
down_revision: Union[str, Sequence[str], None] = 'd629ec20422f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_clients',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id_type', sa.Enum('cedula', 'ruc', 'pasaporte', 'consumidor_final', name='billing_id_type'), nullable=False),
    sa.Column('id_number', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_clients_user_id'), 'billing_clients', ['user_id'], unique=False)
    op.create_table('billing_products',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('has_iva', sa.Boolean(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_products_user_id'), 'billing_products', ['user_id'], unique=False)
    op.create_table('billing_documents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('client_name', sa.String(length=256), nullable=False),
    sa.Column('client_id_number', sa.String(length=32), nullable=True),
    sa.Column('document_type', sa.Enum('quote', name='billing_document_type'), nullable=False),
    sa.Column('quote_number', sa.String(length=16), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('iva_rate', sa.Float(), nullable=False),
    sa.Column('iva_amount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'accepted', 'rejected', 'expired', name='billing_document_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['billing_clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_number')
    )
    op.create_index(op.f('ix_billing_documents_user_id'), 'billing_documents', ['user_id'], unique=False)
    op.create_table('billing_document_items',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('has_iva', sa.Boolean(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['billing_documents.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['billing_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_document_items_document_id'), 'billing_document_items', ['document_id'], unique=False)
    op.add_column('business_info', sa.Column('iva_rate', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_info', 'iva_rate')
    op.drop_index(op.f('ix_billing_document_items_document_id'), table_name='billing_document_items')
    op.drop_table('billing_document_items')
    op.drop_index(op.f('ix_billing_documents_user_id'), table_name='billing_documents')
    op.drop_table('billing_documents')
    op.drop_index(op.f('ix_billing_products_user_id'), table_name='billing_products')
    op.drop_table('billing_products')
    op.drop_index(op.f('ix_billing_clients_user_id'), table_name='billing_clients')
    op.drop_table('billing_clients')
    # ### end Alembic commands ###
