"""add_documents_table

Revision ID: 521a2157c0d3
Revises: d3bd12ec80b6
Create Date: 2026-07-21 16:53:07.091038

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '521a2157c0d3'
down_revision: Union[str, Sequence[str], None] = 'd3bd12ec80b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('cedula', 'pasaporte', 'licencia', 'soat', 'seguro', 'factura', 'garantia', 'certificado', 'escritura', 'contrato', 'tarjeta', 'otro', name='document_type'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('document_number', sa.String(length=128), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('entity_name', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('file_key', sa.String(length=512), nullable=True),
    sa.Column('file_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'archived', name='document_status'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', Vector(dim=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_document_type', 'documents', ['document_type'], unique=False)
    op.create_index('idx_documents_expiry_date', 'documents', ['expiry_date'], unique=False)
    op.create_index('idx_documents_user_id', 'documents', ['user_id'], unique=False)
    op.create_index('idx_documents_user_type', 'documents', ['user_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_documents_expiry_date'), 'documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.drop_index(op.f('ix_shared_expense_participants_expense_id'), table_name='shared_expense_participants')
    op.drop_table('shared_expense_participants')
    op.drop_index(op.f('ix_shared_expenses_user_id'), table_name='shared_expenses')
    op.drop_table('shared_expenses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_expenses',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('split_type', postgresql.ENUM('equal', 'custom', name='split_type'), autoincrement=False, nullable=False),
    sa.Column('expense_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='shared_expenses_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shared_expenses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_shared_expenses_user_id'), 'shared_expenses', ['user_id'], unique=False)
    op.create_table('shared_expense_participants',
    sa.Column('expense_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'paid', name='participant_status'), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('shared_expense_participants_contact_id_fkey')),
    sa.ForeignKeyConstraint(['expense_id'], ['shared_expenses.id'], name=op.f('shared_expense_participants_expense_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shared_expense_participants_pkey'))
    )
    op.create_index(op.f('ix_shared_expense_participants_expense_id'), 'shared_expense_participants', ['expense_id'], unique=False)
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_expiry_date'), table_name='documents')
    op.drop_index('idx_documents_user_type', table_name='documents')
    op.drop_index('idx_documents_user_id', table_name='documents')
    op.drop_index('idx_documents_expiry_date', table_name='documents')
    op.drop_index('idx_documents_document_type', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
