"""add_projects_contacts_expenses_subscriptions

Revision ID: 644fdd6ef5fe
Revises: f7445791d104
Create Date: 2026-07-11 22:06:32.008538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644fdd6ef5fe'
down_revision: Union[str, Sequence[str], None] = 'f7445791d104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('telegram_id', sa.String(length=64), nullable=True),
    sa.Column('whatsapp_id', sa.String(length=64), nullable=True),
    sa.Column('relationship', sa.String(length=64), nullable=True),
    sa.Column('is_emergency_contact', sa.Boolean(), nullable=False),
    sa.Column('contact_notes', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='project_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_user_name', 'projects', ['user_id', 'name'], unique=True)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('shared_expenses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('split_type', sa.Enum('equal', 'custom', name='split_type'), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_expenses_user_id'), 'shared_expenses', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'individual', 'ruc', name='subscription_plan'), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'expired', 'trial', name='subscription_status'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('caregiver_links',
    sa.Column('caregiver_user_id', sa.UUID(), nullable=False),
    sa.Column('cared_for_user_id', sa.UUID(), nullable=False),
    sa.Column('cared_for_contact_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cared_for_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['cared_for_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['caregiver_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caregiver_links_cared_for_user_id'), 'caregiver_links', ['cared_for_user_id'], unique=False)
    op.create_index(op.f('ix_caregiver_links_caregiver_user_id'), 'caregiver_links', ['caregiver_user_id'], unique=False)
    op.create_table('payments',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('gateway', sa.String(length=32), nullable=False),
    sa.Column('gateway_payment_id', sa.String(length=128), nullable=True),
    sa.Column('gateway_status', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_table('project_tasks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', name='task_status'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_tasks_due_date', 'project_tasks', ['due_date'], unique=False)
    op.create_index('idx_project_tasks_project_status', 'project_tasks', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_project_tasks_project_id'), 'project_tasks', ['project_id'], unique=False)
    op.create_table('shared_expense_participants',
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', name='participant_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['shared_expenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_expense_participants_expense_id'), 'shared_expense_participants', ['expense_id'], unique=False)
    op.create_table('subscription_invoices',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('sri_authorization', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_subscription_invoices_payment_id'), 'subscription_invoices', ['payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_invoices_payment_id'), table_name='subscription_invoices')
    op.drop_table('subscription_invoices')
    op.drop_index(op.f('ix_shared_expense_participants_expense_id'), table_name='shared_expense_participants')
    op.drop_table('shared_expense_participants')
    op.drop_index(op.f('ix_project_tasks_project_id'), table_name='project_tasks')
    op.drop_index('idx_project_tasks_project_status', table_name='project_tasks')
    op.drop_index('idx_project_tasks_due_date', table_name='project_tasks')
    op.drop_table('project_tasks')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_caregiver_links_caregiver_user_id'), table_name='caregiver_links')
    op.drop_index(op.f('ix_caregiver_links_cared_for_user_id'), table_name='caregiver_links')
    op.drop_table('caregiver_links')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_shared_expenses_user_id'), table_name='shared_expenses')
    op.drop_table('shared_expenses')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index('idx_projects_user_name', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
