"""add_onboarding_step_to_users

Revision ID: 7fe196cae0dc
Revises: 228f6423df6c
Create Date: 2026-07-19 00:06:08.865543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe196cae0dc'
down_revision: Union[str, Sequence[str], None] = '228f6423df6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('onboarding_step', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # Make plan_id NOT NULL now that all rows have it
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.UUID(),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_step')
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
