"""add_vehicles_and_maintenances

Revision ID: 9a5e88f1a576
Revises: 7fe196cae0dc
Create Date: 2026-07-20 13:04:30.773872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5e88f1a576'
down_revision: Union[str, Sequence[str], None] = '7fe196cae0dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plate', sa.String(length=16), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('engine_number', sa.String(length=64), nullable=True),
    sa.Column('chassis_number', sa.String(length=64), nullable=True),
    sa.Column('last_digit', sa.Integer(), nullable=True),
    sa.Column('pico_y_placa_days', sa.String(length=64), nullable=True),
    sa.Column('next_matriculation', sa.Date(), nullable=True),
    sa.Column('soat_expiry', sa.Date(), nullable=True),
    sa.Column('rtv_expiry', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_plate'), 'vehicles', ['plate'], unique=False)
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.create_table('vehicle_maintenances',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_type', sa.Enum('oil_change', 'brakes', 'tires', 'battery', 'general', 'other', name='maintenance_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.Date(), nullable=True),
    sa.Column('performed_by', sa.String(length=128), nullable=True),
    sa.Column('next_at', sa.Date(), nullable=True),
    sa.Column('next_mileage_km', sa.Integer(), nullable=True),
    sa.Column('receipt_file_key', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_maintenances_vehicle_id'), 'vehicle_maintenances', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_maintenances_vehicle_id'), table_name='vehicle_maintenances')
    op.drop_table('vehicle_maintenances')
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
