"""drop_asset_fk_from_events

Revision ID: a3b9030af8fc
Revises: 6a3e3614d8f1
Create Date: 2026-07-21 16:57:18.854181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3b9030af8fc'
down_revision: Union[str, Sequence[str], None] = '6a3e3614d8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_asset_id_fkey'), 'events', type_='foreignkey')
    op.drop_index(op.f('idx_assets_attributes'), table_name='assets', postgresql_using='gin')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('events_asset_id_fkey'), 'events', 'assets', ['asset_id'], ['id'])
    op.create_table('assets',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_type', postgresql.ENUM('vehicle', 'credit_card', 'warranty', 'subscription', 'document', 'insurance', 'tax', 'property', 'pet', 'other', name='asset_type'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('attributes_schema_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('assets_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('assets_pkey'))
    )
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_index(op.f('idx_assets_attributes'), 'assets', ['attributes'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
