"""add_billing_info_and_invoice_sri_fields

Revision ID: cd15a6ae36bf
Revises: 035570aa5a29
Create Date: 2026-07-22 12:54:13.064136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd15a6ae36bf'
down_revision: Union[str, Sequence[str], None] = '035570aa5a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_info',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('id_number', sa.String(length=32), nullable=False),
    sa.Column('id_type', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_billing_info_user_default', 'billing_info', ['user_id', 'is_default'], unique=False)
    op.create_index(op.f('ix_billing_info_user_id'), 'billing_info', ['user_id'], unique=False)

    # Create invoice_status ENUM before using it
    invoice_status_enum = sa.Enum('issued', 'authorized', 'cancelled', name='invoice_status')
    invoice_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('subscription_invoices', sa.Column('billing_name', sa.String(length=256), nullable=True))
    op.add_column('subscription_invoices', sa.Column('billing_id_number', sa.String(length=32), nullable=True))
    op.add_column('subscription_invoices', sa.Column('billing_id_type', sa.String(length=16), nullable=True))
    op.add_column('subscription_invoices', sa.Column('billing_email', sa.String(length=256), nullable=True))
    op.add_column('subscription_invoices', sa.Column('billing_phone', sa.String(length=32), nullable=True))
    op.add_column('subscription_invoices', sa.Column('billing_address', sa.String(length=512), nullable=True))
    op.add_column('subscription_invoices', sa.Column('status', invoice_status_enum, nullable=False, server_default='issued'))
    op.add_column('subscription_invoices', sa.Column('sri_access_key', sa.String(length=64), nullable=True))
    op.add_column('subscription_invoices', sa.Column('sri_authorization_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_profiles', sa.Column('phone', sa.String(length=32), nullable=True))
    op.add_column('user_profiles', sa.Column('address', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'address')
    op.drop_column('user_profiles', 'phone')
    op.drop_column('subscription_invoices', 'sri_authorization_date')
    op.drop_column('subscription_invoices', 'sri_access_key')
    op.drop_column('subscription_invoices', 'status')
    op.drop_column('subscription_invoices', 'billing_address')
    op.drop_column('subscription_invoices', 'billing_phone')
    op.drop_column('subscription_invoices', 'billing_email')
    op.drop_column('subscription_invoices', 'billing_id_type')
    op.drop_column('subscription_invoices', 'billing_id_number')
    op.drop_column('subscription_invoices', 'billing_name')
    op.drop_index(op.f('ix_billing_info_user_id'), table_name='billing_info')
    op.drop_index('idx_billing_info_user_default', table_name='billing_info')
    op.drop_table('billing_info')
    # ### end Alembic commands ###
