"""initial

Revision ID: d308da353d4f
Revises: 
Create Date: 2026-07-11 18:56:22.003583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'd308da353d4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.String(length=64), nullable=True),
    sa.Column('whatsapp_id', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_whatsapp_id'), 'users', ['whatsapp_id'], unique=True)
    op.create_table('assets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('vehicle', 'credit_card', 'warranty', 'subscription', 'document', 'insurance', 'tax', 'property', 'pet', 'other', name='asset_type'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attributes_schema_version', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assets_attributes', 'assets', ['attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('telegram', 'whatsapp', name='message_channel'), nullable=False),
    sa.Column('message_type', sa.Enum('text', 'audio', 'photo', name='message_type'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('extraction_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('received', 'acked', 'extracted', 'confirmed', 'persisted', 'error', name='message_status'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('persisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('certainty', sa.Enum('certain', 'estimated', name='event_certainty'), nullable=False),
    sa.Column('recurrence_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('upcoming', 'done', 'cancelled', 'overdue', name='event_status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_asset_id'), 'events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_events_target_date'), 'events', ['target_date'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('reminders',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('telegram', 'whatsapp', name='reminder_channel'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'acknowledged', 'failed', name='reminder_status'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_event_id'), 'reminders', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_event_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_target_date'), table_name='events')
    op.drop_index(op.f('ix_events_asset_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_index('idx_assets_attributes', table_name='assets', postgresql_using='gin')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_whatsapp_id'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
