"""add_key49_id_to_invoices

Revision ID: d629ec20422f
Revises: cd15a6ae36bf
Create Date: 2026-07-22 13:01:37.986447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd629ec20422f'
down_revision: Union[str, Sequence[str], None] = 'cd15a6ae36bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_invoices', sa.Column('key49_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_invoices', 'key49_id')
    # ### end Alembic commands ###
